site_name: BuildService 
site_url: https://fittergem.github.io/BuildService
repo_name: fittergem/BuildService
repo_url: https://github.com/fittergem/BuildService

theme:
  icon:
    logo: material/database
  name: material
  #favicon: images/favicon.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.footer
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: light-blue
      accent: white
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: light-blue
      accent: white

nav:
  - Home: index.md
  - API: documentation.md
  - Tutorial: installation.md
  - Support: support.md

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
